#!/usr/bin/env bash
# Options
#  --wallet=[walletname default kdewallet] 
# Refs
## https://github.com/gistya/expandr/blob/master/expandr.sh
## https://unix.stackexchange.com/questions/154485/how-do-i-capture-stdin-to-a-variable-without-stripping-any-trailing-newlines

# todo kwalletcli existance check
# todo erase

# If you want another folde name except "Passwords", You must create the folder first.

FOLDER_NAME=Passwords
KEY_PREFIX="GIT_CREDENTIAL_HELPER_KWALLET-QUERY#"

GIT_CREDENTIAL_INPUT=`cat; echo x`

getParam() {
    PARAM_NAME=$1
    printf "%s" "${GIT_CREDENTIAL_INPUT%x}" | grep -e "^$PARAM_NAME=" | sed "s/^$PARAM_NAME=//"
}

GIT_PROTOCOL=`getParam "protocol"`
GIT_HOST=`getParam "host"`
GIT_USERNAME=`getParam "username"`
GIT_PASSWORD=`getParam "password"`

echo "protocoe ==> $GIT_PROTOCOL"
echo "host ==> $GIT_HOST"
echo "username ==> $GIT_USERNAME"
echo "password ==> $GIT_PASSWORD"

case $1 in
    get)
        storedPassword=`kwallet-query -f ${FOLDER_NAME} -r "${KEY_PREFIX}${GIT_PROTOCOL}://${GIT_USERNAME}@${GIT_HOST}"`
        if [ ! -z $storedPassword ]
        then
            echo "username=$GIT_USERNAME"
            echo "passowrd=$storedPassword"
        fi
        ;;
    store)
        echo "${GIT_PASSWORD}" | kwallet-query -f ${FOLDER_NAME} -w "${KEY_PREFIX}${GIT_PROTOCOL}://${GIT_USERNAME}@${GIT_HOST}"
        ;;
esac
