#!/usr/bin/env bash
# Options
#  --wallet=[walletname default kdewallet] 
# Refs
## https://github.com/gistya/expandr/blob/master/expandr.sh
## https://unix.stackexchange.com/questions/154485/how-do-i-capture-stdin-to-a-variable-without-stripping-any-trailing-newlines
KWALLET_NAME=kdewallet
FOLDER_NAME=gitx

GIT_CREDENTIAL_INPUT=`cat; echo x`

getParam() {
    PARAM_NAME=$1
    printf "%s" "${GIT_CREDENTIAL_INPUT%x}" | grep -e "^$PARAM_NAME=" | sed "s/^$PARAM_NAME=//"
}

GIT_PROTOCOL=`getParam "protocol"`
GIT_HOST=`getParam "host"`
GIT_USERNAME=`getParam "username"`
GIT_PASSWORD=`getParam "password"`

echo "protocoe ==> $GIT_PROTOCOL"
echo "host ==> $GIT_HOST"
echo "username ==> $GIT_USERNAME"
echo "password ==> $GIT_PASSWORD"

case $1 in
    get)
        storedPassword=`kwalletcli -f $FOLDER_NAME -e "$GIT_PROTOCOL://$GIT_USERNAME@$GIT_HOST"`
        if [ ! -z $storedPassword ]
        then
            echo "username=$GIT_USERNAME"
            echo "passowrd=$storedPassword"
        fi
        ;;
    store)
        kwalletcli -f $FOLDER_NAME -e "$GIT_PROTOCOL://$GIT_USERNAME@$GIT_HOST" -p "$GIT_PASSWORD"
        ;;
esac
